[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stackspot-agent-api"
version = "0.0.1"
description = "API for StackSpot Agent interactions"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["dynaconf", "pydantic", "loguru", "requests"]

[project.optional-dependencies]
api = ["fastapi", "uvicorn[standard]"]
dev = [
  "pytest",
  "ruff",
  "black"
]

[project.scripts]
stackspot-agent-api = "stackspot_agent_api.app:chat"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
